[package]
name        = "gluepad"
version     = "0.1.0"
authors     = ["Andrew Hunter <andrew@logicalshift.co.uk>"]
edition     = "2018"

[dependencies]
futures     = "0.1"
gluon       = "0.12"
desync      = "0.4"
